name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Code Update
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '15'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean build publish -x test --refresh-dependencies
      env:
        MAVEN_USERNAME: ${{secrets.MAVEN_USERNAME}}
        MAVEN_PASSWORD: ${{secrets.MAVEN_PASSWORD}}
